- .github/workflows/markdown-lint.yml
- .markdownlint-cli2.cjs
- package-lock.json
- package.json
Add the actual markdown lint CLI.
@justinegeffen @llewellyn-sl 
This summarized what these rules find. Only really the first three might merit a consensus.
This isn't currently enabled, but fires when there's a TAB instead of a SPACE in the text. Can also fire when this happens in code blocks, or code blocks can be ignored and treated as-is.
https://github.com/DavidAnson/markdownlint/blob/v0.33.0/doc/md010.md
This isn't currently enabled. It presents kind of a style preference, and there's no right answer.
I've always preferred a single space for unordered lists, because it's easy and always correct. For enumerated lists, this is harder, because you've got two characters: `1.`
So a _single_ space _after_ means you're at _3_ spaces. Most of markdown is done in 2 or 4 spaces. So you have to …
> Add markdownlint-cli2

- platform_versioned_docs/version-23.3.0/labels/overview.mdx
- platform_versioned_docs/version-23.3.0/resource-labels/overview.mdx
- platform_versioned_docs/version-23.4.0/labels/overview.mdx
- platform_versioned_docs/version-23.4.0/resource-labels/overview.mdx
Update label and resource label limits to 1000 on Labels overview and Resource labels overview pages, versions 23.3 and 23.4.
> Correct label limits

- .github/workflows/no-conflict-markers.yml
This would be cool if it works; supposed to prevent merges if `>>>>>` conflict markers are present, meaning someone accidentally committed a merge conflict block.
> Prevent Git conflict markers from getting published

- package-lock.json
- package.json
- src/css/misc.css
This could be useful.
This needs `vertical-align: middle` CSS. Possibly `margin: -2px` as well.
https://www.npmjs.com/package/mdi-react
> Experimental work in using Material Design icons

- platform_versioned_docs/version-23.4.0/functionality_matrix/functionality_matrix.mdx
* Rename page to be "base versions" instead of mentioning compatibility
* Add missing Platform patch releases, with associated nf-launcher and Nextflow versions
* Add column for Fusion version
* Fix error in `nextflow.config` filename
For reference:
* Nextflow <> Fusion version pairings can be found [here](https://github.com/nextflow-io/nextflow/blob/c713ad510b76e6483d16292b4a66f6eb05773d36/modules/nextflow/src/main/groovy/nextflow/fusion/FusionConfig.groovy#L37).
* Platform <> Launcher version pairings (and so, Nextflow) can be found [here](https://github.com/seqeralabs/platform/blob/b6cc5eaba93b264959d1ae4e827b30969221d61b/tower-services/src/main/groovy/io/seqera/tower/service/TowerServiceImpl.groovy#L43).
@netlify /platform/23.4.0/functionality_matrix
> Update Platform / Nextflow base versions

- platform_versioned_docs/version-23.4.0/data/data-studios.mdx
Changes:
- Clarify default permissions for mounted data links
- Improve docs about stopping a data studio stuck in `starting` state, based on [Slack discussion](https://seqera.slack.com/archives/C053KDKLEQJ/p1715670868181939?thread_ts=1715605682.241119&cid=C053KDKLEQJ)
> Clarify default permissions, and stopping in aws console

- platform_versioned_docs/version-23.4.0/data/data-studios.mdx
- platform_versioned_sidebars/version-23.4.0-sidebars.json
Clean up:
1. Remove all new references to the term "session" - we consistently just call sessions "data studios".
2. Remove incorrect information about non-saved state being lost - we now have session persistence.
3. Add a note that checkpoints/snapshots are created every five minutes in running data studios. Also add to relevant troubleshooting section.
4. Consistently apply formatting for actions.
5. Add default users (`root` and `rstudio`) and how to install system packages using `apt`.
> Pre-Boston clean-up and move to Public Preview

- README.md
Because of
```
- On source page path = /platform/22.4.0/credentials/agent_credentials:
-> linking to ../../../other_docs/guide.mdx (resolved as: /other_docs/guide.mdx)
```
> Add links between doc sets to README

- platform_versioned_docs/version-24.1.1/functionality_matrix/functionality_matrix.mdx
Correct baseline versions page to reflect j17-23.10.1-up1 as the launcher image for ENT 24.1.1, per https://github.com/seqeralabs/platform/blob/v24.1.1-enterprise/tower-services/src/main/groovy/io/seqera/tower/service/TowerServiceImpl.groovy#L43
> Correct nf-launcher for 24.1.1 in baseline versions page

- platform_versioned_docs/version-23.3.0/compute-envs/aws-batch.mdx
Addresses https://seqera.atlassian.net/browse/EDU-156
Note: This change is only in the 23.3 documentation.
> Removed Graviton3 reference in 23.3 documentation

- .github/workflows/links.yml
This adds external link checking as a cron job, daily. It creates a new GitHub issue when there's a new broken link found.
This rapidly checks links within the base repository, but won't check links in any of the sub-modules.
We can probably experiment with this and try to check links against builds instead of source files.
> Add external link checking

- .github/workflows/check-internal-links.yml
So this doesn't actually work, because reasons. ~~Unfortunately the only approach that can work is capturing output directly from Docusaurus, which is probably possible.~~
An approach similar to this can work for external links, but if run too frequently, false positives might emerge. So it can't really be a blocking check.
We can actually just fail the build:
```
Error: Docs markdown link couldn't be resolved: (../../administration/audit-logs.mdx) in "/Users/jboxman/Work/docs/platform_versioned_docs/version-24.1.1/enterprise/configuration/overview.mdx" for version 24.1.1
at Array.forEach (<anonymous>)
```
This does mean builds do not work if there are any broken internal links:
https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks
> Check internal links

- src/css/misc.css
- https://seqera.atlassian.net/browse/EDU-269
This change overrides the existing CSS to provide a cleaner look for `light` and `dark` themes.
cc @justinegeffen @llewellyn-sl
> Adjust details styling

- platform_versioned_docs/version-24.1/getting-started/quickstart-demo/add-pipelines.mdx
- platform_versioned_docs/version-24.1/launch/launchpad.mdx
- platform_versioned_docs/version-24.1/resource-labels/overview.mdx
Docs updates for 24.2:
- Feature: Add flexibility for pipeline names in workspaces
- Feature: Add tag propagation to launch templates
- New launch form is feature-toggled in Cloud — this PR adds an admonition to contact Seqera to enable it.
> 24.2 minor features

- platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
- platform_versioned_docs/version-24.1/compute-envs/azure-batch.mdx
- platform_versioned_docs/version-24.1/compute-envs/eks.mdx
- platform_versioned_docs/version-24.1/compute-envs/gke.mdx
- platform_versioned_docs/version-24.1/compute-envs/google-cloud-batch.mdx
- platform_versioned_docs/version-24.1/compute-envs/google-cloud-lifesciences.mdx
- platform_versioned_docs/version-24.1/compute-envs/hpc.mdx
- platform_versioned_docs/version-24.1/compute-envs/k8s.mdx
Updates staging options instructions to include global NF config field for all compute environment pages. 
PR includes some formatting fixes.
> [24.2 release docs] Add Gobal Nextflow config field to compute environment pages

- platform_versioned_docs/version-24.1/cloud/changelog.mdx
- platform_versioned_docs/version-24.1/enterprise/_templates/docker/docker-compose.yml
- platform_versioned_docs/version-24.1/enterprise/_templates/docker/tower.yml
- platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-cron.yml
- platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-svc.yml
- platform_versioned_docs/version-24.1/enterprise/index.mdx
- platform_versioned_docs/version-24.1/enterprise/release_notes/enterprise_changelog.mdx
- platform_versioned_docs/version-24.1/enterprise/release_notes/enterprise_latest.mdx
- platform_versioned_docs/version-24.1/enterprise/testing.mdx
- platform_versioned_docs/version-24.1/enterprise/upgrade.mdx
- platform_versioned_sidebars/version-24.1-sidebars.json
Removes 24.1.1 upgrade warning from main Enterprise release notes. 
Adds separate Enterprise changelog
Adds Enterprise upgrade guide page, stripping out most upgrade guidance from the release notes page.
Adds 24.1.3 changelog entries.
Adds custom config and admonitions for 24.1.2 upgrade.
> 24.1.3 Enterprise patch release guidance and changelog

- platform_versioned_docs/version-23.1/compute-envs/google-cloud-batch.mdx
- platform_versioned_docs/version-23.2/compute-envs/google-cloud-batch.mdx
- platform_versioned_docs/version-23.3/compute-envs/google-cloud-batch.mdx
- platform_versioned_docs/version-23.4/compute-envs/google-cloud-batch.mdx
- platform_versioned_docs/version-24.1/compute-envs/google-cloud-batch.mdx
Small typo fix in Google Batch CE docs to mention Fusion V2 allows access to GCS-hosted data, instead of S3-hosted data.
> fix: reference to S3-hosted data in GCP CE docs

- platform_versioned_docs/version-24.1/enterprise/data-studios.mdx
Need to double check, but as near as I can tell, the file name is wrong. This corrects it to the proper file to edit. This is for the Docker Compose installation variant for a new install.
Preview: https://deploy-preview-197--seqera-docs.netlify.app/platform/24.1/enterprise/data-studios#procedure
> Fix wrong file name for env file to edit

- static/_redirects
This would avoid a possible double redirect.
> Redirect to correct latest version

- platform_versioned_docs/version-22.4/faqs.mdx
- platform_versioned_docs/version-23.1/faqs.mdx
- platform_versioned_docs/version-23.2/faqs.mdx
- platform_versioned_docs/version-23.3/faqs.mdx
- platform_versioned_docs/version-23.4/faqs.mdx
- platform_versioned_docs/version-24.1/faqs.mdx
This is a minor fix so that these do not fail builds.
> Use code font for URLs to avoid parser error

- platform_versioned_docs/version-24.1/enterprise/docker-compose.mdx
This tidies up.
See our `platform_versioned_docs/version-24.1/enterprise/_templates/docker/docker-compose.yml` for the lack of this service definition.
> Omit service that no longer exists for Docker

- lychee.toml
> Ignore domain that does not resolve any longer

- platform_versioned_docs/version-23.3/enterprise/configuration/pipeline_optimization.mdx
- platform_versioned_docs/version-23.4/enterprise/configuration/pipeline_optimization.mdx
- platform_versioned_docs/version-24.1/enterprise/_templates/k8s/configmap.yml
- platform_versioned_docs/version-24.1/enterprise/configuration/pipeline_optimization.mdx
- https://seqera.atlassian.net/browse/EDU-256
This adds the required variables for the K8s config map. And the missing step from the Docker configuration.
Additionally, this differentiates steps for the database grant commands and removes steps that are not user action.
If this makes sense, should be applied to both sets of Docker instructions as well.
> Update pipeline optimization K8s deployment steps

- platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
This change adds a link to the manual batch setup from the Manual compute environment setup
I had some trouble finding this while doing the manual setup and thought it would be good to link from one to the other.
> Adding Link to Batch Setup

- platform_versioned_docs/version-24.1/compute-envs/google-cloud-batch.mdx
Minor clarification that boot disk represents the persistent storage for all tasks and the head job
> Minor update to clarify how GCP Batch Behaves

- platform_versioned_docs/version-24.1/compute-envs/k8s.mdx
- https://seqera.atlassian.net/browse/EDU-255
So for whatever reason, this does not work for me locally with Docker Desktop K8s. I don't know why. This comes right from the upstream documentation, so I assume it is correct: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount
Someone else would need to validate this on a live cluster, because strangely I cannot.
> Add steps for manually creating API secret

- static/robots.txt
Added `robots.txt` file to docs site to enable Atlassian AI scraping.
[Docosaurus documentation](https://docusaurus.io/docs/seo#robots-file) mentioned that should be added to the `static` folder.
This resolves [BT-125]
[BT-125]: https://seqera.atlassian.net/browse/BT-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BT-125 Add robots.txt file for Atlassian AI scrapping

- docusaurus.config.js
This breaks local live preview feature.
> Disable faster experimental builds to fix previews

- internal/fetch-docs-oss.mjs
> Fix error handling in fetching repos

- platform_versioned_docs/version-23.3/enterprise/configuration/configtables/db_aws.yml
- platform_versioned_docs/version-23.3/enterprise/configuration/configtables/db_yml.yml
- platform_versioned_docs/version-23.4/enterprise/configuration/configtables/db_aws.yml
- platform_versioned_docs/version-23.4/enterprise/configuration/configtables/db_yml.yml
- platform_versioned_docs/version-24.1/enterprise/configuration/configtables/db_aws.yml
- platform_versioned_docs/version-24.1/enterprise/configuration/configtables/db_yml.yml
- platform_versioned_docs/version-24.2/enterprise/configuration/configtables/db_aws.yml
- platform_versioned_docs/version-24.2/enterprise/configuration/configtables/db_yml.yml
In the next Enterprise version, `redisson.*` properties will be deprecated.
- Replace `/redisson/*` references for the AWS parameter store with `TOWER_REDIS_*`.
- Replace `redisson.*` references for the `tower.yml` with `TOWER_REDIS_*`. Setting `TOWER_REDIS_*` values directly in the YAML file (for example, `TOWER_REDIS_URL: redis://...`) in `tower.yml` is feasible.
In fact, the tweak could be backported to previous versions, as the `TOWER_REDIS_*` placeholders were always the source of truth. I doubt any Enterprise users were setting `redisson.*` properties directly, because the H8 2nd-level cache config doesn't know about them and the application would fail to start if they are not properly set.
> Remove references to `redisson.*`  properties

- platform_versioned_docs/version-24.1/enterprise/_templates/k8s/data_studios/proxy.yml
- platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-cron.yml
- platform_versioned_docs/version-24.2/enterprise/_templates/k8s/data_studios/proxy.yml
- platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-cron.yml
- https://seqera.atlassian.net/browse/EDU-266
> Add Data Studios volume mount to backend container

- platform_versioned_docs/version-24.2/enterprise/configuration/overview.mdx
- https://seqera.atlassian.net/browse/PLAT-1059
~~Looks like this became required as far back as 23.3.~~
We're using 6.2 for 24.2+.
cc @llewellyn-sl
> PLAT-1059: Redis 6.2 is required for Enterprise

- platform_versioned_docs/version-24.2/monitoring/audit-logs.mdx
- platform_versioned_docs/version-24.2/monitoring/configtables/log_events.yml
- https://seqera.atlassian.net/browse/EDU-427
Preview not working for this -- puzzling. But the _Files changed_ is correct.
> EDU-427: Add Data Studios events to audit log table

- platform_versioned_docs/version-24.2/data_studios/index.mdx
- https://seqera.atlassian.net/browse/PLAT-997
Targets: 24.2, 24.1
> Add limitation regarding EFS file system

- platform_versioned_docs/version-24.2/launch/launchpad.mdx
Source: https://github.com/seqeralabs/platform/pull/7870
The config profiles dropdown in the launch form is populated by inspecting the pipeline config files. This process supports only a few common syntax patterns in the nextflow config, so we would like to document them so that users know which patterns will work.
The linked PR is a patch for the upcoming enterprise release, but these docs are less urgent. Happy to edit / move this content as you see fit. We just want to document this behavior publicly.
> Document limitations of config profiles detection for dropdown

- platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx
Update admonition on AWS Batch compute environment page to state Amazon Linux 2023 AMI support, per https://github.com/seqeralabs/platform/pull/7734
> Enterprise 24.2: Amazon Linux2023 AMI admonition update

- src/css/main.css
Hi @ewels and @justinegeffen,
I found out that the issue was with the code block component. It wasn't getting the correct width, so it made the component expand too much. This caused the wrapper container to stretch, pushing the navigation to the bottom due to the flex-wrap prop.
> Fixing codeblock component

- platform_versioned_docs/version-24.1/compute-envs/azure-batch.mdx
- platform_versioned_docs/version-24.2/compute-envs/azure-batch.mdx
Since this is now on stable, we can update this to mean the earliest stable Nextflow version.
> Update minimum Nextflow version to use Azure Batch Managed Identities to stable version

- src/css/main.css
Hi! I hardcoded the width of the code wrapper. 
The problem we are facing is that when the codeLine has too many spans, even with overflow set to scroll, the codeLine wrappers occupy the entire width of the page.
> Nav layout issue

- multiqc_docs/sidebar.js
Adds in link in sidebar for new docs page.
To be merged once https://github.com/MultiQC/MultiQC/pull/2915 is merged.
To test:
```bash
git checkout multiqc-sidebar-ai
cd multiqc_docs/multiqc_repo
git checkout ai
git pull
cd ../../
npm run dev
```
> MultiQC sidebar: Add AI page

- changelog/seqera-cloud/v24.2.0_cycle28.mdx
- Added breaking change content to describe new Spot retries behavior.
- Troubleshooting content to follow.
> Added errorStrategy breaking change to cloud changelog

- platform_versioned_docs/version-24.2/compute-envs/azure-batch.mdx
The number still referred to the edge release, unlike <24.1 documentation, so I've updated it.
> Fix minimum nextflow version number for using Azure Managed Identities

- platform_versioned_docs/version-24.2/enterprise/advanced-topics/manual-azure-batch-setup.mdx
There was a mistake in the Azure Batch manual set up walkthrough which was confusing, I've removed it here and made it consistent with other sections.
> Clarify language in Azure Manual set up walkthrough

- static/_redirects
Per https://seqera.slack.com/archives/C040MFU06AE/p1739525549856709?thread_ts=1739489596.578989&cid=C040MFU06AE, adding 301 redirects to catch all Enterprise pages from latest and 24.3 and redirect them to 24.2 
Redirect to be removed when Cloud and ENT major latest versions are on parity.
> Update Enterprise /latest and /24.3 redirects to /24.2

- platform_versioned_docs/version-24.2/compute-envs/azure-batch.mdx
- platform_versioned_docs/version-24.3/compute-envs/azure-batch.mdx
The Azure Batch role name was slightly incorrect, it needed to include the word 'data', i.e. Azure Batch Data Contributor. This PR fixes this.
> fix: Correct Azure Batch role name

- platform_versioned_docs/version-23.4/limits/limits.mdx
- platform_versioned_docs/version-24.1/limits/limits.mdx
- platform_versioned_docs/version-24.2/limits/limits.mdx
- platform_versioned_docs/version-24.3/limits/limits.mdx
- Moved Organizations above Workspaces (Org limits dictate Wksp limits)
- Move Studios into Organization-level group (doesn't need it's own section)
- Reduce number of Free-Tier Organization users to 3 (per new Free-Tier limits)
- Reduce number of concurrent (Active) runs from 5 to 3 (per Sales request) ready for Free-Tier messaging feature release (and reflect current pricing page)
- Update `Free` to `Basic` to reflect the pricing page verbiage
> Reorganize usage limits page

- platform_versioned_docs/version-24.2/data_studios/index.mdx
- platform_versioned_docs/version-24.3/data_studios/index.mdx
Very minor update noting that container registry also includes security scan results and users can inspect container builds.
> Add info about security scan results and inspect container builds

- fusion_docs/guide/snapshots.mdx
- fusion_docs/sidebar.json
Per https://seqera.slack.com/archives/C089B7YM0AK/p1740089792660299.
> Update Fusion Snapshots docs with recommended EC2 instance types and sizing guidance

- platform_versioned_docs/version-24.1/data_studios/index.mdx
- platform_versioned_docs/version-24.2/data_studios/index.mdx
- platform_versioned_docs/version-24.3/data_studios/index.mdx
In the CX/Sales demo it was raised that users should be aware that checkpoints are saved into blob storage, and therefore incur costs.
> [chore] Add warning about blob storage costs associated with checkpoints

- platform_versioned_docs/version-24.2/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json
- platform_versioned_docs/version-24.2/enterprise/_templates/docker/docker-compose.yml
- platform_versioned_docs/version-24.2/enterprise/_templates/k8s/redis.aks.yml
- platform_versioned_docs/version-24.2/enterprise/_templates/k8s/redis.eks.yml
- platform_versioned_docs/version-24.2/enterprise/_templates/k8s/redis.gke.yml
The following updates redis related manifests for `24.X` release notes to have a compatible version of docker - following on from https://github.com/seqeralabs/docs/pull/500
We use this version of Redis for internal preview environments.
> docs: update redis version in manifests

- platform_versioned_docs/version-24.3/troubleshooting_and_faqs/studios_troubleshooting.mdx
Addresses overarching docs issue raised in [PLAT-1794](https://seqera.atlassian.net/browse/PLAT-1794). Although specific library troubleshooting is beyond the scope of docs, this PR outlines when a cached image is used for rebuilding vs. a fresh image pulled and how that may impact build success.
[PLAT-1794]: https://seqera.atlassian.net/browse/PLAT-1794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Troubleshooting failed custom envs - cache vs. fresh pull

- package-lock.json
- package.json
- platform-enterprise_versioned_docs/version-23.1/enterprise/stylesheets/fonts.css
- platform-enterprise_versioned_docs/version-23.1/enterprise/stylesheets/overrides.css
- src/components/Button/styles.module.css
- src/components/Card/styles.module.css
- src/components/Search/AlgoliaSearch.module.css
- src/components/Search/Search.tsx
- src/components/Search/algolia-theme.css
- src/css/fonts/degular.css
- src/css/main.css
- src/css/misc.css
- src/css/search.css
- src/css/theme-colors.css
- src/modules/Homepage/styles.module.css
- src/theme/BlogLayout/styles.module.css
- src/theme/BlogPostItem/Footer/styles.module.css
- src/theme/BlogSidebar/Desktop/styles.module.css
- src/theme/ColorModeToggle/styles.module.css
- src/theme/DocSidebar/Desktop/ProductSwitcher/styles.module.css
- src/theme/DocSidebar/Desktop/styles.module.css
- src/theme/Navbar/Layout/SeqeraHeader/HeaderDesktop/NavItems/styles.module.css
- src/theme/Navbar/MobileSidebar/SeqeraMenu/Category/Products/styles.module.css
- src/theme/Navbar/Search/styles.module.css
The following is an attempt at fixing the code block vertical scrolling in the docs site which can be seen at the following URL for example https://docs.seqera.io/platform-enterprise/25.1/seqerakit/yaml-configuration the "fixed" version can be seen at https://deploy-preview-572--seqera-docs.netlify.app/platform-enterprise/25.1//seqerakit/yaml-configuration 
I managed to track down some conflicting resources between thin-scrollbar & the global theme for all my attempts I could not debug the explicit positioning in CSS required to make this work due to the number of `!important` directives within the codebase so I initially worked on the removal of as many of these as possible resulting in the removal of all `!important` blocks except the following found in …
> fix: Codeblock vertical scrolling EDU-679 / DP-867

- docusaurus.config.js
- src/css/main.css
- src/theme/Logo/index.tsx
-Fix broken 404 from logo in header and footer from API page
-Update caret hover state
Note: Platform API updates are not reflected in the staging deployment urls. 
TODO: links should be reverted once things are in a single build again.
> api bug style fixes

- package-lock.json
- package.json
**Related to:** 
https://seqera.atlassian.net/browse/EDU-643
**Changes made:**
Added an override in package.json to force the use of image-size ^1.2.1 
Updated package-lock.json to reflect this change
The vulnerability affects image-size 1.1.0 → 1.2.0 and 2.0.0 → 2.0.1
Our project uses image-size as a transitive dependency through @docusaurus/mdx-loader
Using the npm overrides feature should ensure we use the patched version.
> EDU-643: adding overrides image-size

- platform-cloud/docs/compute-envs/aws-cloud.md
Wrap only the text in square bracket to not show the full link to AWS docs.
> FSN-515: Fix EC2 key pair hyperlink

- wave_docs/sidebar.json
The following updates the sidebar for content included in this pull request. https://github.com/seqeralabs/wave/pull/843
It is not clear how to trigger a re-pull of this content without a pull request however we're using the sidebar from this repository vs the one included in the wave repo so it felt prudent to update it.
> docs(Wave): Update sidebar for newly released content

- platform-cloud/docs/compute-envs/google-cloud-batch.md
Adds `roles/logging.logViewer` to the list of required IAM permissions for a custom service account. I think without this, users are unable to see the execution log in the console logs for a run on the Platform (see related JIRA issue [here](https://seqera.atlassian.net/browse/PLAT-2753?atlOrigin=eyJpIjoiNTM0NDcyZWFiYzNhNDdjMTg4M2Y3MmU4YWZmYjRkOTgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)).
> docs: add logsViewer to SA permissions list

- fusion_docs/index.md
Fixed the link in the Fusion index page to point to the licencing info, instead of going to the "Contact Us" email form.
> Fusion: Fix link for licensing

- platform-cloud/docs/compute-envs/aws-batch.md
- platform-enterprise_versioned_docs/version-24.2/compute-envs/aws-batch.md
- platform-enterprise_versioned_docs/version-25.1/compute-envs/aws-batch.md
A support issue was raised requesting clarity on the default allocation strategy in AWS Batch. This was confirmed by DevOps.
> Update default Spot price allocation type

- platform-cloud/docs/monitoring/overview.md
Runs launched via Nextflow CLI cannot be saved as pipelines in Platform.
> Add note about runs launched via Nextflow CLI

- scripts/indexDocs.js
- Removed `.replace(/^platform-enterprise_docs\//, '/platform/')` as we're not currently using that directory AFAIK. @gavinelder, can you confirm?
- Renamed references of platform to `platform-cloud` and `platform-enterprise` to fix broken links
> Update URL generation for platform paths

- platform-cloud/docs/studios/overview.md
Closes https://seqera.atlassian.net/browse/EDU-846
@bebosudo, I removed the content completely as it shouldn't be in the Cloud docs. When we have our new search live, it'll be easier for customers to find the information they need in the docs so we don't need to shoe-horn in this sort of cross-reference. :)
> Remove reference to env vars in Cloud docs
