platform_versioned_docs/version-23.3.0/launch/cache-resume.mdx, platform_versioned_docs/version-23.3.0/launch/launchpad.mdx, platform_versioned_docs/version-23.4.0/launch/cache-resume.mdx, platform_versioned_docs/version-23.4.0/launch/launchpad.mdx, platform_versioned_sidebars/version-23.3.0-sidebars.json, platform_versioned_sidebars/version-23.4.0-sidebars.json
Port from https://github.com/seqeralabs/docs_old/pull/98
=> Cache and resume guidance

platform_versioned_docs/version-23.4.0/launch/launchpad.mdx
Align instructions with [new launch form](https://github.com/seqeralabs/platform/pull/6567).
=> Updated launch form instructions

platform_versioned_docs/version-22.4.0/api/overview.mdx, platform_versioned_docs/version-23.1.0/api/overview.mdx, platform_versioned_docs/version-23.2.0/api/overview.mdx, platform_versioned_docs/version-23.3.0/api/overview.mdx
Incorrect URL for API endpoints page.
=> Fixes incorrect API endpoint URL

.github/styles/config/vocabularies/Seqera/accept.txt, .github/workflows/vale.yml, .gitignore, .vale.ini, README.md
Partial configuration.
Adds GitHub Action.
=> Add initial Vale configuration

platform_versioned_docs/version-23.4.0/data/data-studios.mdx
Mostly code font. This fixes issues with misspelling words in Vale that will come up after we adopt it.
cc @justinegeffen @llewellyn-sl
=> Add code font for JupyterLab packages

platform_versioned_docs/version-23.3.0/enterprise/configuration/authentication.mdx, platform_versioned_docs/version-23.4.0/enterprise/configuration/authentication.mdx
Entra added to top bullet list as it was missing.
=> Added Entra to bullet list

platform_versioned_docs/version-23.3.0/monitoring/cloud-costs.mdx, platform_versioned_docs/version-23.3.0/resource-labels/overview.mdx, platform_versioned_docs/version-23.4.0/monitoring/cloud-costs.mdx, platform_versioned_docs/version-23.4.0/resource-labels/overview.mdx
Per https://seqera.slack.com/archives/C040MFU06AE/p1713896688709949
=> Front-load resource labels and cost estimate on cloud costs pages

platform_versioned_docs/version-23.3.0/data/data-explorer.mdx, platform_versioned_docs/version-23.4.0/data/data-explorer.mdx
I think the indentation for these is off, so this indents content to match the list elements.
cc @justinegeffen @llewellyn-sl
=> Fix list indentation

platform_versioned_docs/version-22.4.0/compute-envs/eks.mdx, platform_versioned_docs/version-22.4.0/compute-envs/gke.mdx, platform_versioned_docs/version-22.4.0/compute-envs/k8s.mdx, platform_versioned_docs/version-22.4.0/git/overview.mdx, platform_versioned_docs/version-23.1.0/git/overview.mdx, platform_versioned_docs/version-23.2.0/git/overview.mdx, wave_docs/api.mdx
=> Remove the the

platform_versioned_docs/version-23.3.0/data/data-explorer.mdx, platform_versioned_docs/version-23.4.0/data/data-explorer.mdx
Per Slack: https://seqera.slack.com/archives/C040MFU06AE/p1715199220776299
=> Use seqera.io for Data Explorer CORS headers

platform_versioned_docs/version-23.4.0/data/data-studios.mdx
Fixes https://github.com/seqeralabs/tower-backlog/issues/1215
=> skeleton for data studio checkpoints

platform_versioned_docs/version-23.4.0/data/data-studios.mdx
First pass, needs revisions. Request originated on Slack: https://seqera.slack.com/archives/C053KDKLEQJ/p1714947936506089
=> Add Data Studio 5G overlay file system limit

platform_versioned_docs/version-23.3.0/enterprise/advanced-topics/manual-aws-batch-setup.mdx, platform_versioned_docs/version-23.3.0/launch/cache-resume.mdx, platform_versioned_docs/version-23.4.0/enterprise/advanced-topics/manual-aws-batch-setup.mdx, platform_versioned_docs/version-23.4.0/launch/cache-resume.mdx
=> Fix internal link casualties

.github/styles/config/vocabularies/Seqera/accept.txt
=> Add words to Vale allow list

README.md
This just touches the README for this.
=> Update README for Wave Git submodule use

platform_versioned_docs/version-23.4.0/data/data-studios.mdx
Add note about checkpoint cleanup.
=> checkpoint deletion note

platform_versioned_docs/version-23.4.0/data/data-explorer.mdx
Addresses https://github.com/seqeralabs/platform/issues/6644 and https://github.com/seqeralabs/tower-backlog/issues/1076
=> Data Explorer: Generate download script

docusaurus.config.js
As in topic. This seems to work.
=> Enable GitHub editing for Wave

platform_versioned_docs/version-24.1.0/launch/advanced.mdx, platform_versioned_docs/version-24.1.0/launch/launchpad.mdx
Documents the new launch form. Port from https://github.com/seqeralabs/docs/pull/24/files
=> [24.1] New launch form

platform_versioned_docs/version-24.1.0/enterprise/configuration/configtables/generic_config_aws.yml, platform_versioned_docs/version-24.1.0/enterprise/configuration/configtables/generic_config_env.yml, platform_versioned_docs/version-24.1.0/enterprise/configuration/configtables/generic_config_yml.yml
Added disable email config to environment variables.
=> [24.1] Env vars for disable email login

platform_versioned_docs/version-24.1.0/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json, platform_versioned_docs/version-24.1.0/enterprise/_templates/k8s/tower-cron.yml, platform_versioned_docs/version-24.1.0/enterprise/kubernetes.mdx, platform_versioned_docs/version-24.1.0/enterprise/prerequisites/aws.mdx, platform_versioned_docs/version-24.1.0/enterprise/prerequisites/azure.mdx, platform_versioned_docs/version-24.1.0/enterprise/prerequisites/gcp.mdx, platform_versioned_docs/version-24.1.0/enterprise/prerequisites/on-prem.mdx
=> Try 24.1 images

platform_versioned_docs/version-24.1.0/enterprise/release_notes/22.1.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/22.2.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/22.3.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/22.4.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/23.1.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/23.2.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/23.3.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/23.4.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/enterprise_latest.mdx, platform_versioned_sidebars/version-24.1.0-sidebars.json
Consistent release notes page titles for left nav.
=> Harmonize release notes page titles

platform_versioned_docs/version-24.1.0/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json, platform_versioned_docs/version-24.1.0/enterprise/_templates/docker/docker-compose.yml, platform_versioned_docs/version-24.1.0/enterprise/_templates/k8s/tower-cron.yml, platform_versioned_docs/version-24.1.0/enterprise/_templates/k8s/tower-svc.yml, platform_versioned_docs/version-24.1.0/enterprise/data-studios.mdx, platform_versioned_docs/version-24.1.0/enterprise/index.mdx, platform_versioned_docs/version-24.1.0/enterprise/kubernetes.mdx, platform_versioned_docs/version-24.1.0/enterprise/prerequisites/aws.mdx, platform_versioned_docs/version-24.1.0/enterprise/prerequisites/azure.mdx, platform_versioned_docs/version-24.1.0/enterprise/prerequisites/gcp.mdx, platform_versioned_docs/version-24.1.0/enterprise/prerequisites/on-prem.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/changelog.mdx, platform_versioned_docs/version-24.1.0/enterprise/release_notes/enterprise_latest.mdx, platform_versioned_docs/version-24.1.0/functionality_matrix/functionality_matrix.mdx
Per @swampie  in https://seqera.slack.com/archives/C03KZDQ0UL9/p1719933729785789
=> Update docs to Enterprise 24.1.1 

platform_versioned_docs/version-24.1.1/enterprise/configuration/configtables/generic_config_aws.yml, platform_versioned_docs/version-24.1.1/enterprise/configuration/configtables/generic_config_env.yml, platform_versioned_docs/version-24.1.1/enterprise/configuration/configtables/generic_config_yml.yml
Fixed a font error for disable email entry
=> Config tables: Fixed a formatting error

.github/workflows/links.yml
This should actually work. The other would not check any of our files.
cc @justinegeffen @llewellyn-sl
=> Check MDX files

package-lock.json
=> Touch package-lock.json

platform_versioned_docs/version-23.4.0/data/data-studios.mdx, platform_versioned_docs/version-24.1.1/data/data-studios.mdx
- https://github.com/seqeralabs/tower-backlog/issues/1249
=> Add note about free-tier DS limit

platform_versioned_docs/version-24.1.1/enterprise/release_notes/enterprise_latest.mdx
Per https://seqera.slack.com/archives/C01R00KHL9F/p1721817388586279
=> Add support upgrade warning to Enterprise 24.1 release notes

platform_versioned_docs/version-23.4.0/enterprise/release_notes/changelog.mdx, platform_versioned_docs/version-23.4.0/enterprise/release_notes/enterprise_latest.mdx
Addresses missing information in the release notes (dates added as per the release history in platform repo).
Jira https://seqera.atlassian.net/browse/EDU-270
=> Update: 23.4.x release notes

static/_redirects
=> Add Netlify redirects for version trimming

platform_versioned_docs/version-24.1/enterprise/configuration/configtables/data_features_yml.yml, platform_versioned_docs/version-24.1/enterprise/configuration/overview.mdx
- https://seqera.atlassian.net/browse/EDU-161
Targets 24.1+
=> Add Data Explorer max number of items listed

platform_versioned_docs/version-24.1/cloud/changelog.mdx
Changelog update for cloud release
=> Changelog - 14 August 2024

.github/workflows/links.yml, lychee.toml
Tidies up some loose ends with this.
=> Add external links to ignore list

platform_versioned_docs/version-24.1/enterprise/_templates/docker/docker-compose.yml, platform_versioned_docs/version-24.1/enterprise/_templates/k8s/data_studios/proxy.yml, platform_versioned_docs/version-24.1/enterprise/_templates/k8s/data_studios/server.yml
includes changes needed to make rstudio version 4.4 work
=> update connect images used for enterprise

platform_versioned_docs/version-24.1/enterprise/configuration/configtables/req_env_vars.yml
Updated example to reflect the breaking change parameter in changelog.
=> Updated tower_db_url example

platform_versioned_docs/version-23.3/data/data-explorer.mdx, platform_versioned_docs/version-23.4/data/data-explorer.mdx, platform_versioned_docs/version-24.1/data/data-explorer.mdx
Via: https://seqera.slack.com/archives/C040MFU06AE/p1724256172999599
=> Fix CORS JSON for AWS

platform_versioned_docs/version-23.1/enterprise/index.mdx, platform_versioned_docs/version-23.2/enterprise/index.mdx, platform_versioned_docs/version-23.3/enterprise/index.mdx, platform_versioned_docs/version-23.4/enterprise/index.mdx, platform_versioned_docs/version-24.1/enterprise/index.mdx
- https://seqera.atlassian.net/browse/EDU-308
Change the language for Enterprise install license admonition.
Applies to 24.1, 23.x
=> For Enterprise ask user to contact for license

platform_versioned_docs/version-24.1/data/data-explorer.mdx
- https://seqera.atlassian.net/browse/EDU-52
=> Add text on Data Explorer disabling

platform_versioned_docs/version-24.1/data/data-studios.mdx, platform_versioned_docs/version-24.1/enterprise/data-studios.mdx
- https://seqera.atlassian.net/browse/EDU-300
=> Data Studios requires Data Explorer

platform_versioned_docs/version-23.1/compute-envs/aws-batch.mdx, platform_versioned_docs/version-23.2/compute-envs/aws-batch.mdx, platform_versioned_docs/version-23.3/compute-envs/aws-batch.mdx, platform_versioned_docs/version-23.4/compute-envs/aws-batch.mdx, platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
- https://seqera.atlassian.net/browse/EDU-157
Mention that AWS Batch has a 50 queue batch limit.
Preview: https://deploy-preview-188--seqera-docs.netlify.app/platform/24.1/compute-envs/aws-batch
=> Add note about AWS Batch 50 queue batch limit

package-lock.json, package.json
https://docusaurus.io/blog/releases/3.5
Features of note:
https://docusaurus.io/blog/releases/3.4#tags-files
https://docusaurus.io/blog/releases/3.3#prepare-for-react-19
https://docusaurus.io/blog/releases/3.2#faster-builds
https://docusaurus.io/blog/releases/3.2#faster-dev-server
https://docusaurus.io/blog/releases/3.2#mdx-partials-table-of-contents
https://docusaurus.io/blog/releases/3.1#broken-anchors-checker
=> Upgrade to Docusaurus v3.5.2

src/css/misc.css
- https://seqera.atlassian.net/browse/EDU-311
Example with many lists: https://deploy-preview-214--seqera-docs.netlify.app/platform/24.1/compute-envs/aws-batch
=> Adjust spacing for lists

static/_redirects
=> Add redirects for Wave documentation URL changes

platform_versioned_docs/version-24.1/cloud/changelog.mdx
=> Fixed changelog formatting

platform_versioned_docs/version-24.1/enterprise/_templates/docker/tower.env, platform_versioned_docs/version-24.1/enterprise/_templates/k8s/configmap.yml, platform_versioned_docs/version-24.1/enterprise/data-studios.mdx
- https://seqera.atlassian.net/issues/PLAT-432
- https://seqera.atlassian.net/browse/EDU-316
Specify the latest versions of the images that Data Studios ships. This happens out-of-band from releases.
=> Add Data Studios environment image versions

platform_versioned_sidebars/version-23.2-sidebars.json, platform_versioned_sidebars/version-23.3-sidebars.json, platform_versioned_sidebars/version-23.4-sidebars.json, platform_versioned_sidebars/version-24.1-sidebars.json
This cleans up the sidebars by removing extra spacing.
@llewellyn-sl @justinegeffen
=> Remove extraneous trailing spaces

platform_versioned_docs/version-24.1/limits/limits.mdx
- https://seqera.atlassian.net/browse/EDU-340
- Preview: https://deploy-preview-232--seqera-docs.netlify.app/platform/24.1/limits#data-studio
=> Add running data studios default limit

src/components/Card/styles.module.css
=> Docs homepage: hover colour in light mode for platform

src/css/main.css, src/theme/DocSidebar/Desktop/ProductSwitcher/styles.module.css, src/theme/DocSidebar/Desktop/index.tsx, src/theme/DocSidebar/Desktop/styles.module.css
Hot fixes for new sidebar nav:
* Sticky top fixed, so that the search is no longer hidden when scrolling on long pages
* Overflow-y allowed, so that the sidebar itself can be scrolled when unfurling long lists of nav links.
=> Sidebar scroll bugs

platform_versioned_docs/version-23.4/cli/installation.mdx, platform_versioned_docs/version-24.1/cli/installation.mdx
Per https://seqera.atlassian.net/browse/EDU-1
=> CLI: Add Private CA SSL keystore password instructions

docusaurus.config.js, src/theme/DocSidebar/Desktop/ProductSwitcher/VersionSwitcher.tsx, src/theme/DocSidebar/Desktop/styles.module.css, src/theme/Navbar/Layout/styles.custom.module.css
* Fix "edit this page" link for MultiQC
* Fix the sidebar scroll gradient in dark mode
* Fix the table of contents `top` position, so that you can see the whole TOC when scrolling
* Platform version switcher: keep the current docs page suffix
* NB: If navigating to a page that doesn't exist in the selected version, you'll get a 404 error
=> Docs fixes

platform_versioned_docs/version-23.4/orgs-and-teams/workspace-management.mdx, platform_versioned_docs/version-24.1/orgs-and-teams/workspace-management.mdx
Per https://seqera.slack.com/archives/C040MFU06AE/p1727787306076039
=> Fix "local workspace" wording

platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
=> Added missing link to AWS quotas page

platform_versioned_docs/version-23.4/enterprise/configuration/overview.mdx, platform_versioned_docs/version-24.1/enterprise/configuration/overview.mdx
Per https://seqera.slack.com/archives/C040MFU06AE/p1726689884207429
=> Add API rate limit env vars

platform_versioned_docs/version-24.1/compute-envs/hpc.mdx, platform_versioned_docs/version-24.1/supported_software/agent/agent.mdx
- https://seqera.atlassian.net/browse/EDU-317
=> Add env variables for the agent

platform_versioned_docs/version-24.1/monitoring/dashboard.mdx
Addresses https://seqera.atlassian.net/browse/PLAT-728
=> Added two statuses to DS dashboard content

platform_versioned_docs/version-24.1/data_studios/managing.mdx, platform_versioned_docs/version-24.1/enterprise/docker-compose.mdx, platform_versioned_docs/version-24.1/enterprise/kubernetes.mdx, platform_versioned_docs/version-24.1/getting-started/proteinfold.mdx, platform_versioned_docs/version-24.1/getting-started/quickstart-demo/comm-showcase.mdx, platform_versioned_docs/version-24.1/getting-started/quickstart-demo/data-studios.mdx, platform_versioned_docs/version-24.1/getting-started/rnaseq.mdx, platform_versioned_docs/version-24.1/troubleshooting_and_faqs/data_studios_troubleshooting.mdx, platform_versioned_docs/version-24.2/data_studios/managing.mdx, platform_versioned_docs/version-24.2/enterprise/docker-compose.mdx, platform_versioned_docs/version-24.2/enterprise/kubernetes.mdx, platform_versioned_docs/version-24.2/getting-started/proteinfold.mdx, platform_versioned_docs/version-24.2/getting-started/quickstart-demo/comm-showcase.mdx, platform_versioned_docs/version-24.2/getting-started/quickstart-demo/data-studios.mdx, platform_versioned_docs/version-24.2/getting-started/rnaseq.mdx, platform_versioned_docs/version-24.2/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
Would need to apply to 24.2 as well if approved.
Applying on top of 24.2 docs port, to be rebased to master.
=> Use interactive analysis

docusaurus.config.js, package-lock.json, package.json
This upgrades Docusaurus to 3.6 and enables the new experimental build system.
=> Upgrade Docusaurus and enable new build system

platform_versioned_docs/version-23.4/getting-started/workspace-setup.mdx, platform_versioned_docs/version-24.1/getting-started/workspace-setup.mdx, platform_versioned_docs/version-24.2/getting-started/workspace-setup.mdx
=> Fix Wesbite

platform_versioned_docs/version-23.1/enterprise/release_notes/22.4.mdx, platform_versioned_docs/version-23.4/launch/advanced.mdx
Updated outdated blog link.
- added in a second update which I mistakenly added to this branch.
=> Update link to blog

platform_versioned_docs/version-23.3/secrets/overview.mdx, platform_versioned_docs/version-23.4/launch/launchpad.mdx, platform_versioned_docs/version-23.4/secrets/overview.mdx, platform_versioned_docs/version-24.1/launch/launchpad.mdx, platform_versioned_docs/version-24.1/secrets/overview.mdx, platform_versioned_docs/version-24.2/launch/launchpad.mdx, platform_versioned_docs/version-24.2/secrets/overview.mdx
Per https://seqera.atlassian.net/browse/EDU-24
=> [EDU-24] Add custom job definition admonition for secrets

platform_versioned_docs/version-23.3/compute-envs/aws-batch.mdx, platform_versioned_docs/version-23.3/compute-envs/overview.mdx, platform_versioned_docs/version-23.4/compute-envs/aws-batch.mdx, platform_versioned_docs/version-23.4/compute-envs/overview.mdx, platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx, platform_versioned_docs/version-24.1/compute-envs/overview.mdx, platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx, platform_versioned_docs/version-24.2/compute-envs/overview.mdx
Per https://seqera.atlassian.net/browse/PLAT-756
=> Add NVIDIA GPU support note

platform_versioned_docs/version-22.4/compute-envs/overview.mdx, platform_versioned_docs/version-23.1/compute-envs/overview.mdx, platform_versioned_docs/version-23.3/compute-envs/overview.mdx, platform_versioned_docs/version-23.4/compute-envs/overview.mdx, platform_versioned_docs/version-24.1/compute-envs/overview.mdx, platform_versioned_docs/version-24.2/compute-envs/overview.mdx
- https://seqera.slack.com/archives/C040MFU06AE/p1732803250849139
=> Use more complex example for AWS Batch UseGPU

.github/styles/config/vocabularies/Seqera/accept.txt, .github/workflows/vale.yml, .gitignore, .vale.ini
Explores using Vale on either built HTML or on MDXv3 files with creatively crafted skip and ignore rules for unrecognized MDX features.
=> Vale exploratory work

platform_versioned_docs/version-24.1/data_studios/custom-envs.mdx, platform_versioned_docs/version-24.2/data_studios/custom-envs.mdx
- https://seqera.atlassian.net/browse/PLAT-1057
Aplies to 24.2, 24.1
=> PLAT-1057: Fix DS custom env YAML example

package-lock.json, package.json
Final patch release upgrade for the year.
=> Upgrade to latest Docusaurus 3.6.3 release

src/theme/Admonition/index.js
=> feat: Ensure Warning admontations are Warnings

platform_versioned_docs/version-24.1/troubleshooting_and_faqs/data_studios_troubleshooting.mdx, platform_versioned_docs/version-24.2/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
Capitalization was not in line with most recent discussion.
@deepcshah, adding you for visibility.
=> [Data Studios] Revising capitalization

static/_redirects
- Added a new redirect
- Replaced version number with `latest`
=> [Platform] Update redirects with new entry: CLI docs

changelog/seqera-enterprise/v23.4.mdx
Removed "major" from the title.
=> Renamed 23.4 file for consistency

package-lock.json, package.json
This ought to apply the changes that GitHub identifies collectively, instead of individually.
=> Apply npm audit changes

platform_versioned_docs/version-24.1/data_studios/index.mdx
- https://seqera.atlassian.net/browse/PLAT-997
This was missing.
https://github.com/seqeralabs/docs/pull/333
=> PLAT-997: Add EFS limitation

platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx
- https://seqera.atlassian.net/browse/EDU-469
=> Update Data Explorer AWS policies

changelog/seqera-enterprise/v24.2.2.mdx, changelog/seqera-enterprise/v24.2.mdx, platform_versioned_docs/version-24.2/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json, platform_versioned_docs/version-24.2/enterprise/_templates/docker/docker-compose.yml, platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-cron.yml, platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-svc.yml, platform_versioned_docs/version-24.2/enterprise/index.mdx, platform_versioned_docs/version-24.2/enterprise/kubernetes.mdx, platform_versioned_docs/version-24.2/enterprise/prerequisites/aws.mdx, platform_versioned_docs/version-24.2/enterprise/prerequisites/azure.mdx, platform_versioned_docs/version-24.2/enterprise/prerequisites/gcp.mdx, platform_versioned_docs/version-24.2/enterprise/prerequisites/on-prem.mdx
Updates container image URLs and changelog for Enterprise v24.2.2
=> Bump v24.2.2, add changelog items

platform_versioned_docs/version-24.1/data_studios/custom-envs.mdx, platform_versioned_docs/version-24.2/data_studios/custom-envs.mdx
Minor change, drop unnecessary field.
cc @ewels
=> Drop unnecessary name field from env file

changelog/seqera-enterprise/v24.2.mdx, platform_versioned_docs/version-24.2/data_studios/index.mdx
Fixes https://seqera.atlassian.net/browse/EDU-440
=> [EDU-440] EFS volume mounting content update

package-lock.json, package.json
- https://seqera.atlassian.net/browse/EDU-484
=> Upgrade to latest Dinosaur

changelog/seqera-enterprise/v24.2.mdx
- https://seqera.atlassian.net/browse/EDU-500
=> Clarify Data Studios GPU and CPU availability

changelog/seqera-enterprise/v23.3.mdx, changelog/seqera-enterprise/v23.4.mdx, changelog/seqera-enterprise/v24.2.mdx, platform_versioned_docs/version-23.3/enterprise/release_notes/enterprise_latest.mdx, platform_versioned_docs/version-24.2/enterprise/prerequisites/azure.mdx
- https://seqera.atlassian.net/browse/EDU-379
=> Add steps to handle Azure MySQL foreign keys

platform_versioned_docs/version-23.4/data/data-explorer.mdx, platform_versioned_docs/version-24.1/data/data-explorer.mdx, platform_versioned_docs/version-24.2/data/data-explorer.mdx
=> Fix link anchor for UI code

scripts/indexDocs.js
=> updated Algolia variables in scripts

.github/styles/config/vocabularies/Seqera/accept.txt, platform_versioned_docs/version-24.1/data_studios/managing.mdx, platform_versioned_docs/version-24.2/data_studios/index.mdx, platform_versioned_docs/version-24.2/data_studios/managing.mdx
- https://seqera.atlassian.net/browse/EDU-488
=> EDU-488: Update Vale word list

platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-cron.yml, platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-svc.yml, platform_versioned_docs/version-24.1/enterprise/data-studios.mdx, platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-cron.yml, platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-svc.yml, platform_versioned_docs/version-24.2/enterprise/data-studios.mdx
- https://seqera.atlassian.net/browse/EDU-593
=> Apply Data Studios change to tower-svc.yml

platform_versioned_docs/version-24.2/data_studios/index.mdx
Closes [PLAT-1467](https://seqera.atlassian.net/browse/PLAT-1467)
[PLAT-1467]: https://seqera.atlassian.net/browse/PLAT-1467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update with NF and NF language server

changelog/fusion/v2.4.4.mdx, changelog/fusion/v2.5.0.mdx, changelog/fusion/v2.5.1.mdx, changelog/seqera-cloud/v24.2.0_cycle28.mdx
This PR adds the fusion changelogs for versions v2.5.0 and v2.5.1
=> add fusion changelogs for v2.5.0 and v2.5.1

platform_versioned_docs/version-24.2/enterprise/advanced-topics/manual-azure-batch-setup.mdx
The Azure Batch advanced section was a placeholder so I've clarified what the document is for.
=> Clarify Azure Batch walkthrough

platform_versioned_docs/version-24.2/troubleshooting_and_faqs/data_studios_troubleshooting.mdx, platform_versioned_docs/version-24.3/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
Closes [PLAT-1521](https://seqera.atlassian.net/browse/PLAT-1521).
[PLAT-1521]: https://seqera.atlassian.net/browse/PLAT-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add info about security scan false positives

static/_redirects
Update redirect to new version.
=> Update _redirects with new version

platform_versioned_docs/version-24.2/getting-started/quickstart-demo/add-pipelines.mdx, platform_versioned_docs/version-24.2/launch/launchpad.mdx
Closes https://seqera.atlassian.net/browse/PLAT-1205?atlOrigin=eyJpIjoiZmY4YTE1ZTdjYzI0NGI5MDgxMzBmNTIxYzdiMjYwNTMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ. 
**To be merged when the feature goes live.**
Feature can be tested at https://pr-8003.dev-tower.net/.
=> [PLAT-1205] Add pipeline image upload instructions

platform_versioned_docs/version-24.2/getting-started/quickstart-demo/add-pipelines.mdx, platform_versioned_docs/version-24.2/launch/launchpad.mdx
=> Revert "[PLAT-1205] Add pipeline image upload instructions"

src/modules/Homepage/index.tsx
- Update to cloud links rather than enterprise links.
=> Update cloud links

platform_versioned_docs/version-23.3/enterprise/release_notes/changelog.mdx, platform_versioned_docs/version-23.4/enterprise/release_notes/changelog.mdx, platform_versioned_docs/version-24.1/cloud/changelog.mdx, platform_versioned_docs/version-24.2/cloud/changelog.mdx, platform_versioned_docs/version-24.3/cloud/changelog.mdx
- Remove note formatting from changelog
=> Remove changelog note

platform_versioned_docs/version-24.2/limits/limits.mdx, platform_versioned_docs/version-24.3/limits/limits.mdx
Closes https://seqera.atlassian.net/browse/PLAT-628
=> [PLAT-628] Add academic and PoC usage limits admonition and CTA to contact sales

platform_versioned_docs/version-23.3/enterprise/advanced-topics/firewall-configuration.mdx, platform_versioned_docs/version-23.4/enterprise/advanced-topics/firewall-configuration.mdx, platform_versioned_docs/version-24.1/enterprise/advanced-topics/firewall-configuration.mdx, platform_versioned_docs/version-24.2/enterprise/advanced-topics/firewall-configuration.mdx
Solves https://seqera.atlassian.net/browse/DEVOPS-305 and https://seqera.atlassian.net/browse/EDU-609.
Not sure all endpoints are required for enterprise customers, we may want to double check.
=> Add all public endpoints to list of domains to allow in firewalls

fusion_docs/guide.mdx, fusion_docs/index.mdx, fusion_docs/licensing.mdx
Adds Fusion licensing content to documentation.
=> Add Fusion licensing content

fusion_docs/licensing.mdx, fusion_docs/sidebar.json
- Added to sidebar
- Decreased header sizes
=> [Fusion licensing] Update sidebar.json

platform_versioned_docs/version-24.3/monitoring/configtables/log_events.yml
Closes [PLAT-1532](https://seqera.atlassian.net/browse/PLAT-1532)
[PLAT-1532]: https://seqera.atlassian.net/browse/PLAT-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add audit event log for pipeline edits

platform_versioned_docs/version-24.3/studios/managing.mdx
Describes a best effort to migrate a Studio from a `deprecated` container template to a new one using `latest`.
=> [Chore] New section on migrating Studios

platform_versioned_docs/version-24.2/troubleshooting_and_faqs/nextflow.mdx
Revision of the previous PR due to merge conflict issues.
=> Revision of max retries update

platform_versioned_docs/version-22.4/compute-envs/aws-batch.mdx, platform_versioned_docs/version-23.1/compute-envs/aws-batch.mdx, platform_versioned_docs/version-23.2/compute-envs/aws-batch.mdx, platform_versioned_docs/version-23.3/compute-envs/aws-batch.mdx, platform_versioned_docs/version-23.4/compute-envs/aws-batch.mdx, platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx, platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx, platform_versioned_docs/version-24.3/compute-envs/aws-batch.mdx
Per https://seqera.slack.com/archives/C040MFU06AE/p1741857709389249
=> Update AWS Batch min CPUs warning

platform_versioned_docs/version-24.2/data_studios/custom-envs.mdx, platform_versioned_docs/version-24.2/enterprise/studios.mdx, platform_versioned_docs/version-24.3/studios/custom-envs.mdx
- Update to the latest images
- Add note on `recommended` and `deprecated` tags
=> Update container template images and add note on new tags

platform_versioned_docs/version-24.3/studios/managing.mdx
Documents https://seqera.atlassian.net/browse/PLAT-1041 and minor restructure of the page: https://deploy-preview-520--seqera-docs.netlify.app/platform/24.3/studios/managing
=> [Studios] Add Privacy

platform_versioned_docs/version-24.2/enterprise/studios.mdx
Incorrect link was failing the internal link checker.
=> [Fix] Link fix for Studios in Enterprise docs

fusion_docs/guide/aws-batch.mdx, fusion_docs/guide/aws-eks.mdx, fusion_docs/guide/gcp-gke.mdx, fusion_docs/guide/local/oracle-object.mdx
=> Fix placeholders in fusion docs

platform_versioned_docs/version-25.1/studios/managing.mdx
- Updated "data-link" to "data link"
- Message rewording in cloud bucket section
- UI casing fix
- Added correct label name
=> Correction of "data-link" in Studios docs

platform-enterprise_versioned_docs/version-25.1/enterprise/_templates/docker/docker-compose.yml
Update connect version for dockerfile.
=> update images in compose files for connect

platform-cloud/docs/studios/index.mdx
Minor fix - remove old content.
=> Studios - public preview fix.

platform-enterprise_versioned_docs/version-25.1/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json, platform-enterprise_versioned_docs/version-25.1/enterprise/_templates/docker/docker-compose.yml, platform-enterprise_versioned_docs/version-25.1/enterprise/index.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/kubernetes.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/aws.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/azure.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/gcp.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/on-prem.mdx
Per https://seqera.slack.com/archives/C040MFU06AE/p1744278459527809
=> Fix 25.1.0 image URLs

platform-cloud/docs/monitoring/configtables/log_events.yml, platform-enterprise_versioned_docs/version-23.4/enterprise/docker-compose.mdx, platform-enterprise_versioned_docs/version-23.4/enterprise/upgrade.mdx, platform-enterprise_versioned_docs/version-24.1/enterprise/data-studios.mdx, platform-enterprise_versioned_docs/version-24.1/enterprise/docker-compose.mdx, platform-enterprise_versioned_docs/version-24.1/enterprise/testing.mdx, platform-enterprise_versioned_docs/version-24.1/enterprise/upgrade.mdx, platform-enterprise_versioned_docs/version-24.2/enterprise/docker-compose.mdx, platform-enterprise_versioned_docs/version-24.2/enterprise/studios.mdx, platform-enterprise_versioned_docs/version-24.2/enterprise/testing.mdx, platform-enterprise_versioned_docs/version-24.2/enterprise/upgrade.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/docker-compose.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/studios.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/testing.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/upgrade.mdx, platform-enterprise_versioned_docs/version-25.1/monitoring/configtables/log_events.yml, platform-enterprise_versioned_sidebars/version-23.4-sidebars.json, platform-enterprise_versioned_sidebars/version-24.1-sidebars.json, platform-enterprise_versioned_sidebars/version-24.2-sidebars.json
Small post-versioning fixes, and elaborating on CE and pipeline edit events on the audit logs page.
=> Minor Enterprise IA improvements, audit log events table update

platform-enterprise_versioned_docs/version-25.1/enterprise/studios.mdx
Added note about `TOOL` config setting. 
Fixes https://seqera.atlassian.net/browse/EDU-674
=> [EDU-674] Studios: config note for 25.1

platform-cloud/docs/compute-envs/azure-batch.mdx, platform-enterprise_versioned_docs/version-23.1/enterprise/prerequisites/azure.mdx, platform-enterprise_versioned_docs/version-23.2/enterprise/prerequisites/azure.mdx, platform-enterprise_versioned_docs/version-23.3/enterprise/prerequisites/azure.mdx, platform-enterprise_versioned_docs/version-23.4/enterprise/prerequisites/azure.mdx, platform-enterprise_versioned_docs/version-24.1/enterprise/prerequisites/azure.mdx, platform-enterprise_versioned_docs/version-24.2/compute-envs/azure-batch.mdx, platform-enterprise_versioned_docs/version-24.2/enterprise/prerequisites/azure.mdx, platform-enterprise_versioned_docs/version-25.1/compute-envs/azure-batch.mdx, platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/azure.mdx
Azure Ubuntu 20.04 is leaving LTS and therefore EOL. This PR updates our docs to reflect the new recommended image.
=> Update Azure VM images from Ubuntu 20.04

src/theme/BlogSidebar/Desktop/index.js
Cloud and Enterprise are now separate docs, so simpler logic for directing back from the two changelog tags.
@netlify /changelog/seqera-cloud/
=> Fix logic for changelog sidenav.

platform-cloud/docs/compute-envs/aws-batch.mdx, platform-enterprise_versioned_docs/version-25.1/compute-envs/aws-batch.mdx
Added content from https://github.com/seqeralabs/docs/pull/567 to Enterprise page for consistency.
=> Update to AWS Batch page (caveat)

platform-cloud/docs/compute-envs/aws-batch.mdx, platform-enterprise_versioned_docs/version-25.1/compute-envs/aws-batch.mdx
As that part was never merged.
=> AWS Batch doc caveat removes reference to API response

platform-cloud/docs/compute-envs/aws-cloud.md
=> Header fix for AWS Cloud

src/modules/Homepage/index.tsx
Updated link to Cloud overview
=> Update docs landing page

platform-cloud/docs/studios/overview.md
- Simplify language
- Remove multiple links to same docs page
=> Add AWS Cloud CE type and remove Batch-centric language

platform-cloud/docs/studios/custom-envs.md
Update to match the sidebar help (in-flight) User Story [PLAT-2333](https://seqera.atlassian.net/browse/PLAT-2333)
[PLAT-2333]: https://seqera.atlassian.net/browse/PLAT-2333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update conda overview and links; update Wave service links

platform-enterprise_versioned_docs/version-25.2/data/data-explorer.md
Add Data Explorer multi-file upload to Enterprise docs.
=> [Ent 25.2] Data explorer multiple file upload

docusaurus.config.js
- Add configuration to ignore untruncated blog post warning
=> Ignore untruncated blog post warning

platform-cloud/docs/compute-envs/azure-batch.md, platform-cloud/docs/enterprise/advanced-topics/manual-azure-batch-setup.md, platform-cloud/docs/troubleshooting_and_faqs/azure_troubleshooting.md, platform-enterprise_versioned_docs/version-23.3/faqs.md, platform-enterprise_versioned_docs/version-23.4/faqs.md, platform-enterprise_versioned_docs/version-24.1/troubleshooting_and_faqs/azure_troubleshooting.md, platform-enterprise_versioned_docs/version-24.2/compute-envs/azure-batch.md, platform-enterprise_versioned_docs/version-24.2/enterprise/advanced-topics/manual-azure-batch-setup.md, platform-enterprise_versioned_docs/version-24.2/troubleshooting_and_faqs/azure_troubleshooting.md, platform-enterprise_versioned_docs/version-25.1/compute-envs/azure-batch.md, platform-enterprise_versioned_docs/version-25.1/enterprise/advanced-topics/manual-azure-batch-setup.md, platform-enterprise_versioned_docs/version-25.1/troubleshooting_and_faqs/azure_troubleshooting.md
Azure Low Priority VMs are being removed after September 2025. This PR removes all references to them or adds a warning saying which circumstances you can use them.
=> Remove references to Azure Low Priority VMs

platform-cloud/docs/orgs-and-teams/workspace-management.md
Resolves https://seqera.atlassian.net/browse/EDU-415
=> Add note about shared Studios sessions

fusion_docs/guide/aws-eks.md, fusion_docs/guide/snapshots.md, platform-cloud/docs/compute-envs/aws-batch.md, platform-cloud/docs/compute-envs/azure-batch.md, platform-cloud/docs/compute-envs/eks.md, platform-cloud/docs/compute-envs/gke.md, platform-cloud/docs/compute-envs/google-cloud-batch.md, platform-cloud/docs/compute-envs/seqera-compute.md, platform-cloud/docs/enterprise/advanced-topics/manual-azure-batch-setup.md, platform-cloud/docs/getting-started/proteinfold.md, platform-cloud/docs/getting-started/rnaseq.md, platform-cloud/docs/getting-started/studios.md, platform-cloud/docs/studios/overview.md
Rename "Pipeline work directory" to "Work directory" in CE forms. 
Fixes **https://seqera.atlassian.net/browse/EDU-767**
=> [PLAT-2455] Rename "Pipeline work directory" to "Work directory"

changelog/seqera-cloud/v25.2.0_cycle16.md
=> Release notes for  cycle 16

changelog/seqera-enterprise/v24.2.5.md
As per https://seqera.slack.com/archives/C040MFU06AE/p1752253746670019
=> Renamed incorrectly named version

fusion_docs/licensing.md
They request to update the wrong URL here
https://seqera.slack.com/archives/C05L50LUX8S/p1752490450245589
=> Updating fusion licensing URL

src/components/Search/Search.tsx
Bug fix: when scrolling, the search bar results modal disappears.
=> search bar scroll fix

platform-cloud/docs/studios/overview.md
1. Update VSCode version and included libraries (Python and Pip), including versions.
2. Add path-based routing to Limitations section.
3. Move Limitations section to the foot of the page.
=> Add path-based routing and update VSCode version and included libraries

src/theme/Navbar/Layout/SeqeraHeader/HeaderDesktop/NavItems/index.jsx
- Change hardcoded `25.1` to `latest`
=> Fix version hardcode

changelog/seqera-enterprise/v24.1.md, fusion_docs/licensing.md, platform-cloud/docs/studios/custom-envs.md, platform-enterprise_versioned_docs/version-23.3/enterprise/advanced-topics/db-docker-to-RDS.md, platform-enterprise_versioned_docs/version-23.3/enterprise/kubernetes.mdx, platform-enterprise_versioned_docs/version-23.3/enterprise/prerequisites/aws.mdx, platform-enterprise_versioned_docs/version-23.3/enterprise/prerequisites/azure.md, platform-enterprise_versioned_docs/version-23.3/enterprise/prerequisites/on-prem.md, platform-enterprise_versioned_docs/version-23.3/git/overview.md, platform-enterprise_versioned_docs/version-23.4/administration/overview.md, platform-enterprise_versioned_docs/version-23.4/faqs.md, platform-enterprise_versioned_docs/version-25.2/administration/overview.md, platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/configtables/crypto_aws.yml, platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/configtables/crypto_env.yml, platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/configtables/crypto_yml.yml, platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/overview.mdx, platform-enterprise_versioned_docs/version-25.2/enterprise/docker-compose.md, platform-enterprise_versioned_docs/version-25.2/enterprise/kubernetes.md, src/css/main.css
Documenting Secret key rotation feature for Enterprise 25.2 release. 
@netlify /platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/overview.mdx#secret-key-rotation
=> [PLAT-2107] Secret key rotation docs 

platform-enterprise_versioned_docs/version-25.2/troubleshooting_and_faqs/studios_troubleshooting.md
Fixes https://seqera.atlassian.net/browse/PLAT-1676
@t0randr, do we want to keep the old content related to the AWS console or remove it completely?
=> [Troubleshooting] Studio stuck in starting update

platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/aws_parameter_store.md, platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/configtables/compute_env.yml, platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/configtables/data_features_env.yml
Section to review is: https://deploy-preview-748--seqera-docs.netlify.app/platform-enterprise/25.2/enterprise/configuration/overview#data-features
=> Update to env vars for 25.2

platform-enterprise_versioned_docs/version-25.2/enterprise/upgrade.md
Version 25.2 considerations, breaking changes, and installation upgrade guidance
=> Enterprise 25.2 upgrade guidance

.github/styles/config/vocabularies/Seqera/reject.txt
- [Dd]ata was causing a lot of failures. Removed from reject list.
=> [fix] Removed 'data' reject - Vale

platform-cloud/docs/data/data-explorer.md, platform-enterprise_versioned_docs/version-23.4/data/data-explorer.md, platform-enterprise_versioned_docs/version-24.1/data/data-explorer.md, platform-enterprise_versioned_docs/version-24.2/data/data-explorer.md, platform-enterprise_versioned_docs/version-25.1/data/data-explorer.md
Updating format of "data-links" to align with what we use in CLI docs.
=> data links to data-links

platform-cloud/docs/compute-envs/google-cloud.md
=> [minor-fix] Incorrect spacing

changelog/seqera-cloud/v25.1.0_cycle11.md, docusaurus.config.js, src/modules/Homepage/index.tsx, src/theme/Navbar/Layout/SeqeraHeader/HeaderDesktop/NavItems/index.jsx, static/_redirects
Update `/platform-api/seqera-api` > `/platform-api/info/seqera-api`
=> Fix API docs links

fusion_docs/guide/aws-batch.md
Recommendations to make the non-NVMe suggestion a little more guarded.
=> Clarification for storage recommendations when using Fusion
